# coding: utf-8

"""
    DocuSign Rooms API - v2

    An API for an integrator to access the features of DocuSign Rooms  # noqa: E501

    OpenAPI spec version: v2
    Contact: devcenter@docusign.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class CustomData(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'is_required_on_create': 'bool',
        'is_required_on_submit': 'bool'
    }

    attribute_map = {
        'is_required_on_create': 'isRequiredOnCreate',
        'is_required_on_submit': 'isRequiredOnSubmit'
    }

    def __init__(self, is_required_on_create=None, is_required_on_submit=None):  # noqa: E501
        """CustomData - a model defined in Swagger"""  # noqa: E501

        self._is_required_on_create = None
        self._is_required_on_submit = None
        self.discriminator = None

        if is_required_on_create is not None:
            self.is_required_on_create = is_required_on_create
        if is_required_on_submit is not None:
            self.is_required_on_submit = is_required_on_submit

    @property
    def is_required_on_create(self):
        """Gets the is_required_on_create of this CustomData.  # noqa: E501


        :return: The is_required_on_create of this CustomData.  # noqa: E501
        :rtype: bool
        """
        return self._is_required_on_create

    @is_required_on_create.setter
    def is_required_on_create(self, is_required_on_create):
        """Sets the is_required_on_create of this CustomData.


        :param is_required_on_create: The is_required_on_create of this CustomData.  # noqa: E501
        :type: bool
        """

        self._is_required_on_create = is_required_on_create

    @property
    def is_required_on_submit(self):
        """Gets the is_required_on_submit of this CustomData.  # noqa: E501


        :return: The is_required_on_submit of this CustomData.  # noqa: E501
        :rtype: bool
        """
        return self._is_required_on_submit

    @is_required_on_submit.setter
    def is_required_on_submit(self, is_required_on_submit):
        """Sets the is_required_on_submit of this CustomData.


        :param is_required_on_submit: The is_required_on_submit of this CustomData.  # noqa: E501
        :type: bool
        """

        self._is_required_on_submit = is_required_on_submit

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CustomData, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CustomData):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
