# coding: utf-8

"""
    DocuSign Rooms API - v2

    An API for an integrator to access the features of DocuSign Rooms  # noqa: E501

    OpenAPI spec version: v2
    Contact: devcenter@docusign.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class ESignPermissionProfile(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'e_sign_permission_profile_id': 'str',
        'name': 'str',
        'settings': 'ESignAccountRoleSettings'
    }

    attribute_map = {
        'e_sign_permission_profile_id': 'eSignPermissionProfileId',
        'name': 'name',
        'settings': 'settings'
    }

    def __init__(self, e_sign_permission_profile_id=None, name=None, settings=None):  # noqa: E501
        """ESignPermissionProfile - a model defined in Swagger"""  # noqa: E501

        self._e_sign_permission_profile_id = None
        self._name = None
        self._settings = None
        self.discriminator = None

        if e_sign_permission_profile_id is not None:
            self.e_sign_permission_profile_id = e_sign_permission_profile_id
        if name is not None:
            self.name = name
        if settings is not None:
            self.settings = settings

    @property
    def e_sign_permission_profile_id(self):
        """Gets the e_sign_permission_profile_id of this ESignPermissionProfile.  # noqa: E501


        :return: The e_sign_permission_profile_id of this ESignPermissionProfile.  # noqa: E501
        :rtype: str
        """
        return self._e_sign_permission_profile_id

    @e_sign_permission_profile_id.setter
    def e_sign_permission_profile_id(self, e_sign_permission_profile_id):
        """Sets the e_sign_permission_profile_id of this ESignPermissionProfile.


        :param e_sign_permission_profile_id: The e_sign_permission_profile_id of this ESignPermissionProfile.  # noqa: E501
        :type: str
        """

        self._e_sign_permission_profile_id = e_sign_permission_profile_id

    @property
    def name(self):
        """Gets the name of this ESignPermissionProfile.  # noqa: E501


        :return: The name of this ESignPermissionProfile.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this ESignPermissionProfile.


        :param name: The name of this ESignPermissionProfile.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def settings(self):
        """Gets the settings of this ESignPermissionProfile.  # noqa: E501


        :return: The settings of this ESignPermissionProfile.  # noqa: E501
        :rtype: ESignAccountRoleSettings
        """
        return self._settings

    @settings.setter
    def settings(self, settings):
        """Sets the settings of this ESignPermissionProfile.


        :param settings: The settings of this ESignPermissionProfile.  # noqa: E501
        :type: ESignAccountRoleSettings
        """

        self._settings = settings

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ESignPermissionProfile, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ESignPermissionProfile):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
