# coding: utf-8

"""
    DocuSign Rooms API - v2

    An API for an integrator to access the features of DocuSign Rooms  # noqa: E501

    OpenAPI spec version: v2
    Contact: devcenter@docusign.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from docusign_rooms.client.configuration import Configuration


class FieldSet(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'field_set_id': 'str',
        'title': 'str',
        'fields': 'list[Field]'
    }

    attribute_map = {
        'field_set_id': 'fieldSetId',
        'title': 'title',
        'fields': 'fields'
    }

    def __init__(self, _configuration=None, **kwargs):  # noqa: E501
        """FieldSet - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._field_set_id = None
        self._title = None
        self._fields = None
        self.discriminator = None

        setattr(self, "_{}".format('field_set_id'), kwargs.get('field_set_id', None))
        setattr(self, "_{}".format('title'), kwargs.get('title', None))
        setattr(self, "_{}".format('fields'), kwargs.get('fields', None))

    @property
    def field_set_id(self):
        """Gets the field_set_id of this FieldSet.  # noqa: E501


        :return: The field_set_id of this FieldSet.  # noqa: E501
        :rtype: str
        """
        return self._field_set_id

    @field_set_id.setter
    def field_set_id(self, field_set_id):
        """Sets the field_set_id of this FieldSet.


        :param field_set_id: The field_set_id of this FieldSet.  # noqa: E501
        :type: str
        """

        self._field_set_id = field_set_id

    @property
    def title(self):
        """Gets the title of this FieldSet.  # noqa: E501


        :return: The title of this FieldSet.  # noqa: E501
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title):
        """Sets the title of this FieldSet.


        :param title: The title of this FieldSet.  # noqa: E501
        :type: str
        """

        self._title = title

    @property
    def fields(self):
        """Gets the fields of this FieldSet.  # noqa: E501


        :return: The fields of this FieldSet.  # noqa: E501
        :rtype: list[Field]
        """
        return self._fields

    @fields.setter
    def fields(self, fields):
        """Sets the fields of this FieldSet.


        :param fields: The fields of this FieldSet.  # noqa: E501
        :type: list[Field]
        """

        self._fields = fields

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(FieldSet, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, FieldSet):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, FieldSet):
            return True

        return self.to_dict() != other.to_dict()
