# coding: utf-8

"""
    DocuSign Rooms API - v2

    An API for an integrator to access the features of DocuSign Rooms  # noqa: E501

    OpenAPI spec version: v2
    Contact: devcenter@docusign.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class GlobalTransactionSides(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'transaction_sides': 'list[TransactionSide]'
    }

    attribute_map = {
        'transaction_sides': 'transactionSides'
    }

    def __init__(self, transaction_sides=None):  # noqa: E501
        """GlobalTransactionSides - a model defined in Swagger"""  # noqa: E501

        self._transaction_sides = None
        self.discriminator = None

        if transaction_sides is not None:
            self.transaction_sides = transaction_sides

    @property
    def transaction_sides(self):
        """Gets the transaction_sides of this GlobalTransactionSides.  # noqa: E501


        :return: The transaction_sides of this GlobalTransactionSides.  # noqa: E501
        :rtype: list[TransactionSide]
        """
        return self._transaction_sides

    @transaction_sides.setter
    def transaction_sides(self, transaction_sides):
        """Sets the transaction_sides of this GlobalTransactionSides.


        :param transaction_sides: The transaction_sides of this GlobalTransactionSides.  # noqa: E501
        :type: list[TransactionSide]
        """

        self._transaction_sides = transaction_sides

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(GlobalTransactionSides, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GlobalTransactionSides):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
