# coding: utf-8

"""
    DocuSign Rooms API - v2

    An API for an integrator to access the features of DocuSign Rooms  # noqa: E501

    OpenAPI spec version: v2
    Contact: devcenter@docusign.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class GlobalClosingStatuses(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'closing_statuses': 'list[ClosingStatus]'
    }

    attribute_map = {
        'closing_statuses': 'closingStatuses'
    }

    def __init__(self, closing_statuses=None):  # noqa: E501
        """GlobalClosingStatuses - a model defined in Swagger"""  # noqa: E501

        self._closing_statuses = None
        self.discriminator = None

        if closing_statuses is not None:
            self.closing_statuses = closing_statuses

    @property
    def closing_statuses(self):
        """Gets the closing_statuses of this GlobalClosingStatuses.  # noqa: E501


        :return: The closing_statuses of this GlobalClosingStatuses.  # noqa: E501
        :rtype: list[ClosingStatus]
        """
        return self._closing_statuses

    @closing_statuses.setter
    def closing_statuses(self, closing_statuses):
        """Sets the closing_statuses of this GlobalClosingStatuses.


        :param closing_statuses: The closing_statuses of this GlobalClosingStatuses.  # noqa: E501
        :type: list[ClosingStatus]
        """

        self._closing_statuses = closing_statuses

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(GlobalClosingStatuses, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GlobalClosingStatuses):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
