# coding: utf-8

"""
    DocuSign Rooms API - v2

    An API for an integrator to access the features of DocuSign Rooms  # noqa: E501

    OpenAPI spec version: v2
    Contact: devcenter@docusign.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from docusign_rooms.client.configuration import Configuration


class RoleForCreate(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'is_external': 'bool',
        'permissions': 'Permissions'
    }

    attribute_map = {
        'name': 'name',
        'is_external': 'isExternal',
        'permissions': 'permissions'
    }

    def __init__(self, _configuration=None, **kwargs):  # noqa: E501
        """RoleForCreate - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._name = None
        self._is_external = None
        self._permissions = None
        self.discriminator = None

        setattr(self, "_{}".format('name'), kwargs.get('name', None))
        setattr(self, "_{}".format('is_external'), kwargs.get('is_external', None))
        setattr(self, "_{}".format('permissions'), kwargs.get('permissions', None))

    @property
    def name(self):
        """Gets the name of this RoleForCreate.  # noqa: E501


        :return: The name of this RoleForCreate.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this RoleForCreate.


        :param name: The name of this RoleForCreate.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def is_external(self):
        """Gets the is_external of this RoleForCreate.  # noqa: E501


        :return: The is_external of this RoleForCreate.  # noqa: E501
        :rtype: bool
        """
        return self._is_external

    @is_external.setter
    def is_external(self, is_external):
        """Sets the is_external of this RoleForCreate.


        :param is_external: The is_external of this RoleForCreate.  # noqa: E501
        :type: bool
        """

        self._is_external = is_external

    @property
    def permissions(self):
        """Gets the permissions of this RoleForCreate.  # noqa: E501


        :return: The permissions of this RoleForCreate.  # noqa: E501
        :rtype: Permissions
        """
        return self._permissions

    @permissions.setter
    def permissions(self, permissions):
        """Sets the permissions of this RoleForCreate.


        :param permissions: The permissions of this RoleForCreate.  # noqa: E501
        :type: Permissions
        """

        self._permissions = permissions

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(RoleForCreate, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, RoleForCreate):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, RoleForCreate):
            return True

        return self.to_dict() != other.to_dict()
