# coding: utf-8

"""
    DocuSign Rooms API - v2

    An API for an integrator to access the features of DocuSign Rooms  # noqa: E501

    OpenAPI spec version: v2
    Contact: devcenter@docusign.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class RoleSummary(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'role_id': 'int',
        'legacy_role_id': 'str',
        'name': 'str',
        'is_default_for_admin': 'bool',
        'is_external': 'bool',
        'created_date': 'datetime'
    }

    attribute_map = {
        'role_id': 'roleId',
        'legacy_role_id': 'legacyRoleId',
        'name': 'name',
        'is_default_for_admin': 'isDefaultForAdmin',
        'is_external': 'isExternal',
        'created_date': 'createdDate'
    }

    def __init__(self, role_id=None, legacy_role_id=None, name=None, is_default_for_admin=None, is_external=None, created_date=None):  # noqa: E501
        """RoleSummary - a model defined in Swagger"""  # noqa: E501

        self._role_id = None
        self._legacy_role_id = None
        self._name = None
        self._is_default_for_admin = None
        self._is_external = None
        self._created_date = None
        self.discriminator = None

        if role_id is not None:
            self.role_id = role_id
        if legacy_role_id is not None:
            self.legacy_role_id = legacy_role_id
        if name is not None:
            self.name = name
        if is_default_for_admin is not None:
            self.is_default_for_admin = is_default_for_admin
        if is_external is not None:
            self.is_external = is_external
        if created_date is not None:
            self.created_date = created_date

    @property
    def role_id(self):
        """Gets the role_id of this RoleSummary.  # noqa: E501


        :return: The role_id of this RoleSummary.  # noqa: E501
        :rtype: int
        """
        return self._role_id

    @role_id.setter
    def role_id(self, role_id):
        """Sets the role_id of this RoleSummary.


        :param role_id: The role_id of this RoleSummary.  # noqa: E501
        :type: int
        """

        self._role_id = role_id

    @property
    def legacy_role_id(self):
        """Gets the legacy_role_id of this RoleSummary.  # noqa: E501


        :return: The legacy_role_id of this RoleSummary.  # noqa: E501
        :rtype: str
        """
        return self._legacy_role_id

    @legacy_role_id.setter
    def legacy_role_id(self, legacy_role_id):
        """Sets the legacy_role_id of this RoleSummary.


        :param legacy_role_id: The legacy_role_id of this RoleSummary.  # noqa: E501
        :type: str
        """

        self._legacy_role_id = legacy_role_id

    @property
    def name(self):
        """Gets the name of this RoleSummary.  # noqa: E501


        :return: The name of this RoleSummary.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this RoleSummary.


        :param name: The name of this RoleSummary.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def is_default_for_admin(self):
        """Gets the is_default_for_admin of this RoleSummary.  # noqa: E501


        :return: The is_default_for_admin of this RoleSummary.  # noqa: E501
        :rtype: bool
        """
        return self._is_default_for_admin

    @is_default_for_admin.setter
    def is_default_for_admin(self, is_default_for_admin):
        """Sets the is_default_for_admin of this RoleSummary.


        :param is_default_for_admin: The is_default_for_admin of this RoleSummary.  # noqa: E501
        :type: bool
        """

        self._is_default_for_admin = is_default_for_admin

    @property
    def is_external(self):
        """Gets the is_external of this RoleSummary.  # noqa: E501


        :return: The is_external of this RoleSummary.  # noqa: E501
        :rtype: bool
        """
        return self._is_external

    @is_external.setter
    def is_external(self, is_external):
        """Sets the is_external of this RoleSummary.


        :param is_external: The is_external of this RoleSummary.  # noqa: E501
        :type: bool
        """

        self._is_external = is_external

    @property
    def created_date(self):
        """Gets the created_date of this RoleSummary.  # noqa: E501


        :return: The created_date of this RoleSummary.  # noqa: E501
        :rtype: datetime
        """
        return self._created_date

    @created_date.setter
    def created_date(self, created_date):
        """Sets the created_date of this RoleSummary.


        :param created_date: The created_date of this RoleSummary.  # noqa: E501
        :type: datetime
        """

        self._created_date = created_date

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(RoleSummary, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, RoleSummary):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
