# coding: utf-8

"""
    DocuSign Rooms API - v2

    An API for an integrator to access the features of DocuSign Rooms  # noqa: E501

    OpenAPI spec version: v2
    Contact: devcenter@docusign.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class RoleForUpdate(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'is_external': 'bool',
        'permissions': 'Permissions'
    }

    attribute_map = {
        'name': 'name',
        'is_external': 'isExternal',
        'permissions': 'permissions'
    }

    def __init__(self, name=None, is_external=None, permissions=None):  # noqa: E501
        """RoleForUpdate - a model defined in Swagger"""  # noqa: E501

        self._name = None
        self._is_external = None
        self._permissions = None
        self.discriminator = None

        if name is not None:
            self.name = name
        if is_external is not None:
            self.is_external = is_external
        if permissions is not None:
            self.permissions = permissions

    @property
    def name(self):
        """Gets the name of this RoleForUpdate.  # noqa: E501


        :return: The name of this RoleForUpdate.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this RoleForUpdate.


        :param name: The name of this RoleForUpdate.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def is_external(self):
        """Gets the is_external of this RoleForUpdate.  # noqa: E501


        :return: The is_external of this RoleForUpdate.  # noqa: E501
        :rtype: bool
        """
        return self._is_external

    @is_external.setter
    def is_external(self, is_external):
        """Sets the is_external of this RoleForUpdate.


        :param is_external: The is_external of this RoleForUpdate.  # noqa: E501
        :type: bool
        """

        self._is_external = is_external

    @property
    def permissions(self):
        """Gets the permissions of this RoleForUpdate.  # noqa: E501


        :return: The permissions of this RoleForUpdate.  # noqa: E501
        :rtype: Permissions
        """
        return self._permissions

    @permissions.setter
    def permissions(self, permissions):
        """Sets the permissions of this RoleForUpdate.


        :param permissions: The permissions of this RoleForUpdate.  # noqa: E501
        :type: Permissions
        """

        self._permissions = permissions

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(RoleForUpdate, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, RoleForUpdate):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
