# coding: utf-8

"""
    DocuSign Rooms API - v2

    An API for an integrator to access the features of DocuSign Rooms  # noqa: E501

    OpenAPI spec version: v2
    Contact: devcenter@docusign.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class RoomFolder(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'room_folder_id': 'int',
        'name': 'str',
        'is_default': 'bool'
    }

    attribute_map = {
        'room_folder_id': 'roomFolderId',
        'name': 'name',
        'is_default': 'isDefault'
    }

    def __init__(self, room_folder_id=None, name=None, is_default=None):  # noqa: E501
        """RoomFolder - a model defined in Swagger"""  # noqa: E501

        self._room_folder_id = None
        self._name = None
        self._is_default = None
        self.discriminator = None

        if room_folder_id is not None:
            self.room_folder_id = room_folder_id
        if name is not None:
            self.name = name
        if is_default is not None:
            self.is_default = is_default

    @property
    def room_folder_id(self):
        """Gets the room_folder_id of this RoomFolder.  # noqa: E501


        :return: The room_folder_id of this RoomFolder.  # noqa: E501
        :rtype: int
        """
        return self._room_folder_id

    @room_folder_id.setter
    def room_folder_id(self, room_folder_id):
        """Sets the room_folder_id of this RoomFolder.


        :param room_folder_id: The room_folder_id of this RoomFolder.  # noqa: E501
        :type: int
        """

        self._room_folder_id = room_folder_id

    @property
    def name(self):
        """Gets the name of this RoomFolder.  # noqa: E501


        :return: The name of this RoomFolder.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this RoomFolder.


        :param name: The name of this RoomFolder.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def is_default(self):
        """Gets the is_default of this RoomFolder.  # noqa: E501


        :return: The is_default of this RoomFolder.  # noqa: E501
        :rtype: bool
        """
        return self._is_default

    @is_default.setter
    def is_default(self, is_default):
        """Sets the is_default of this RoomFolder.


        :param is_default: The is_default of this RoomFolder.  # noqa: E501
        :type: bool
        """

        self._is_default = is_default

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(RoomFolder, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, RoomFolder):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
