# coding: utf-8

"""
    DocuSign Rooms API - v2

    An API for an integrator to access the features of DocuSign Rooms  # noqa: E501

    OpenAPI spec version: v2
    Contact: devcenter@docusign.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class TransactionSide(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'transaction_side_id': 'str',
        'name': 'str'
    }

    attribute_map = {
        'transaction_side_id': 'transactionSideId',
        'name': 'name'
    }

    def __init__(self, transaction_side_id=None, name=None):  # noqa: E501
        """TransactionSide - a model defined in Swagger"""  # noqa: E501

        self._transaction_side_id = None
        self._name = None
        self.discriminator = None

        if transaction_side_id is not None:
            self.transaction_side_id = transaction_side_id
        if name is not None:
            self.name = name

    @property
    def transaction_side_id(self):
        """Gets the transaction_side_id of this TransactionSide.  # noqa: E501


        :return: The transaction_side_id of this TransactionSide.  # noqa: E501
        :rtype: str
        """
        return self._transaction_side_id

    @transaction_side_id.setter
    def transaction_side_id(self, transaction_side_id):
        """Sets the transaction_side_id of this TransactionSide.


        :param transaction_side_id: The transaction_side_id of this TransactionSide.  # noqa: E501
        :type: str
        """

        self._transaction_side_id = transaction_side_id

    @property
    def name(self):
        """Gets the name of this TransactionSide.  # noqa: E501


        :return: The name of this TransactionSide.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this TransactionSide.


        :param name: The name of this TransactionSide.  # noqa: E501
        :type: str
        """

        self._name = name

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(TransactionSide, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TransactionSide):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
